name: MooProgressBar
author: Rocka84
category: widgets
tags: [progress]
#docs: http://fabian.dillmeier.de/demos/MooProgressBar/index.html
demo: http://fabian.dillmeier.de/demos/MooProgressBar/index.html
current: 1.0