name: MooProgressBar
author: Rocka84
category: widgets
tags: [progress]
#docs: http://dillmeier.de/fabian/demos/MooProgressBar/index.html
demo: http://dillmeier.de/fabian/demos/MooProgressBar/index.html
current: 1.0